
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.AWTException;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author iabdu
 */
public class Student extends javax.swing.JFrame {
String eemail,resultCardstuName,resultcardFname;
    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
         setLocationRelativeTo(null);
    }
 public Student(String a) {
        initComponents();
        setLocationRelativeTo(null);
        email.setText(a);
        eemail=a;
        
        try{  
        Class.forName("com.mysql.jdbc.Driver");  
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cms","root","")) {
           Statement stmt=con.createStatement();
               ResultSet rs=stmt.executeQuery("select * from accepted_requests where email= '"+eemail+"' ");
                while(rs.next()){
                    name.setText(rs.getString(1));
                    fname.setText(rs.getString(2));
                    cnic.setText(rs.getString(3));
                    cont.setText(rs.getString(4));
                    add.setText(rs.getString(5));
                   
                    //for result card storing values in global variales
                    resultCardstuName=rs.getString(1);
                    resultcardFname=rs.getString(2);
                    

                }
        
        
        }//end of inner try
    }//end if outer try
            catch(Exception e){ System.out.println(e);}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        parent = new javax.swing.JPanel();
        dashboard = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        cnic = new javax.swing.JLabel();
        cont = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Anouncement = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ltsann = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        anntable = new javax.swing.JTable();
        Result = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        emailres = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        fnameres = new javax.swing.JLabel();
        stunameres = new javax.swing.JLabel();
        tgrade = new javax.swing.JLabel();
        tmarks = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        cmarks = new javax.swing.JLabel();
        umarks = new javax.swing.JLabel();
        emarks = new javax.swing.JLabel();
        mmarks = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        cgrade = new javax.swing.JLabel();
        ugrade = new javax.swing.JLabel();
        mgrade = new javax.swing.JLabel();
        egrade = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Dashboard");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 211, 131, -1));

        jButton4.setText("Result");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 293, 131, -1));

        jButton5.setText("Change Password");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 334, 131, -1));

        jButton6.setText("Signout");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 375, 131, -1));

        jButton7.setText("Announcement");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 252, 131, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/man icon.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 43, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Welcome ");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 149, 178, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 500));

        parent.setBackground(new java.awt.Color(255, 0, 51));
        parent.setForeground(new java.awt.Color(255, 0, 0));
        parent.setLayout(new java.awt.CardLayout());

        dashboard.setBackground(new java.awt.Color(255, 153, 0));
        dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Name");
        dashboard.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 151, 85, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Email");
        dashboard.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 190, 85, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Father name ");
        dashboard.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 229, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("CNIC");
        dashboard.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Address");
        dashboard.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 189, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Contact");
        dashboard.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 228, -1, -1));

        add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("...");
        add.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 0)));
        dashboard.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 189, 131, -1));

        cnic.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cnic.setForeground(new java.awt.Color(255, 255, 255));
        cnic.setText("...");
        cnic.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 0)));
        dashboard.add(cnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 150, 131, -1));

        cont.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cont.setForeground(new java.awt.Color(255, 255, 255));
        cont.setText("...");
        cont.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 0)));
        dashboard.add(cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 228, 131, -1));

        email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("...");
        email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 0)));
        dashboard.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 190, 131, -1));

        fname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fname.setForeground(new java.awt.Color(255, 255, 255));
        fname.setText("...");
        fname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 0)));
        dashboard.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 229, 131, -1));

        name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("...");
        name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 0)));
        dashboard.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 151, 131, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Sparkle Learn School");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel10)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        dashboard.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, 60));

        parent.add(dashboard, "card3");

        Anouncement.setBackground(new java.awt.Color(255, 153, 0));
        Anouncement.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Announcement");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Anouncement.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 26, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Latest Announcement");
        Anouncement.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 108, 180, 30));

        ltsann.setText("....");
        Anouncement.add(ltsann, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 144, 440, 30));

        anntable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Announcement"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(anntable);

        Anouncement.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 180, -1, 270));

        parent.add(Anouncement, "card2");

        Result.setBackground(new java.awt.Color(255, 153, 0));
        Result.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Government School");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 220, -1));

        emailres.setText("...");
        emailres.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(emailres, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 120, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Email");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 60, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Student Name");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Father Name");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        fnameres.setText("...");
        fnameres.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(fnameres, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 120, -1));

        stunameres.setText("...");
        stunameres.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(stunameres, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 120, -1));

        tgrade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tgrade.setText("...");
        tgrade.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(tgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 40, -1));

        tmarks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tmarks.setText("...");
        tmarks.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(tmarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 40, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Urdu");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("Subject");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("Math");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("Computer");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setText("English");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setText("Marks");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        cmarks.setText("...");
        cmarks.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(cmarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 40, -1));

        umarks.setText("...");
        umarks.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(umarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 40, -1));

        emarks.setText("...");
        emarks.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(emarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 40, -1));

        mmarks.setText("...");
        mmarks.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(mmarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 40, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel37.setText("Grade");
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        cgrade.setText("...");
        cgrade.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(cgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 40, -1));

        ugrade.setText("...");
        ugrade.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(ugrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 40, -1));

        mgrade.setText("...");
        mgrade.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(mgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 40, -1));

        egrade.setText("...");
        egrade.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(egrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 40, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setText("Batch 2023-2024");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school.png"))); // NOI18N
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel14.setText("The Deails of Marks obtained by the candidate is as under");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Errors and Omissions are Excepted");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("Total");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel27)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 232, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, 280));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student.png"))); // NOI18N
        jPanel6.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 68, -1));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 80, 80));

        Result.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 370, 480));

        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Result.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 70, -1));

        parent.add(Result, "card4");

        getContentPane().add(parent, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 540, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        parent.removeAll();
        parent.add(Anouncement);
        parent.repaint();
        parent.revalidate();
       
         String arr []= new String [1];
          try{  
        Class.forName("com.mysql.jdbc.Driver");  
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cms","root","")) {
           Statement stmt=con.createStatement();
             ResultSet rs=stmt.executeQuery("select * from announcement ");
              DefaultTableModel dtm = (DefaultTableModel)anntable.getModel();
             
                    while(rs.next()){
                        
                        arr[0]=rs.getString(1);
                        dtm.addRow(arr);
                        ltsann.setText(arr[0]);
                       
                    }//end of while
                    
      
            
         }//end of inner try
    }//end if outer try
            catch(Exception e){ System.out.println(e);}
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        login lg=new login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 forgot_Password fg= new  forgot_Password();
 fg.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String x=null,y=null,z=null,a=null,b=null,c=null,d=null,e=null,f=null,g=null,h=null;
        parent.removeAll();
        parent.add(Result);
        parent.repaint();
        parent.revalidate();
        
        stunameres.setText(resultCardstuName);
        fnameres.setText(resultcardFname);
        emailres.setText(eemail);
        
        
        try{  
        Class.forName("com.mysql.jdbc.Driver");  
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cms","root","")) {
           Statement stmt=con.createStatement();
             ResultSet rs=stmt.executeQuery("select * from result where cemail='"+eemail+"' ");
                   
                    while(rs.next()){
                        stunameres.setText(resultCardstuName);
                        fnameres.setText(resultcardFname);
               // Retrieve values from specific columns in the result set
                      x=  rs.getString(1);
                      y= rs.getString(2);
                      z= rs.getString(3);
                      a= rs.getString(4);
                      b= rs.getString(5);
                      c= rs.getString(6);
                      d= rs.getString(7);
                      e= rs.getString(8);
                      f= rs.getString(9);
                      g= rs.getString(10);
                      h= rs.getString(11);
                       
                       
                    }//end of while
                    
      stmt.executeUpdate("delete from signup where email= '"+email+"' ");
            
         }//end of inner try
    }//end if outer try
            catch(Exception ee){ System.out.println(ee);}
        
   // Set the text of some components  to values obtained from the result set
        mmarks.setText(y);
        emarks.setText(z);
        umarks.setText(a);
        cmarks.setText(b);
        tmarks.setText(c);
        mgrade.setText(d);
        egrade.setText(e);
        ugrade.setText(f);
        cgrade.setText(g);
        tgrade.setText(h);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        parent.removeAll();
        parent.add(dashboard);
        parent.repaint();
        parent.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // Create Robot instance
            Robot robot = new Robot();

            // Capture the whole screen
            Rectangle screenRect = new Rectangle(Toolkit.getDefaultToolkit().getScreenSize());
            BufferedImage screenFullImage = robot.createScreenCapture(screenRect);

            // Save the screenshot where you want just change the path
            File outputFile = new File("C:\\Users\\Administrator\\Pictures\\Screenshots/resultcard" + ".png" );
            ImageIO.write(screenFullImage, "png", outputFile);
            JOptionPane.showMessageDialog(null,"Screenshot saved Successfully ");

        } catch (AWTException | IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Anouncement;
    private javax.swing.JPanel Result;
    private javax.swing.JLabel add;
    private javax.swing.JTable anntable;
    private javax.swing.JLabel cgrade;
    private javax.swing.JLabel cmarks;
    private javax.swing.JLabel cnic;
    private javax.swing.JLabel cont;
    private javax.swing.JPanel dashboard;
    private javax.swing.JLabel egrade;
    private javax.swing.JLabel email;
    private javax.swing.JLabel emailres;
    private javax.swing.JLabel emarks;
    private javax.swing.JLabel fname;
    private javax.swing.JLabel fnameres;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ltsann;
    private javax.swing.JLabel mgrade;
    private javax.swing.JLabel mmarks;
    private javax.swing.JLabel name;
    private javax.swing.JPanel parent;
    private javax.swing.JLabel stunameres;
    private javax.swing.JLabel tgrade;
    private javax.swing.JLabel tmarks;
    private javax.swing.JLabel ugrade;
    private javax.swing.JLabel umarks;
    // End of variables declaration//GEN-END:variables
}
